on:
  push:
    branches: master

name: Rebuild Website

jobs:
  render:
    name: Rebuild Website
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: Install postcards
        run: Rscript -e 'install.packages("postcards")'
        
      - name: Install distill
        run: Rscript -e 'install.packages("distill")'
        
      - name: Render index file
        run: Rscript -e 'rmarkdown::render_site()'
        
      - name: Render Rmarkdown files and Commit Results
        run: |
          git add .
          git commit -m 'Re-build website' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
